import * as fs from 'fs';
import * as path from 'path';
import type { CLICommand } from '../types.js';

const AGENT_DOCS = {
  claude: { filename: 'CLAUDE.md', format: 'markdown' },
  cursor: { filename: '.cursorrules', format: 'markdown' },
  codex: { filename: 'AGENTS.md', format: 'markdown' },
} as const;

export const initCommand: CLICommand = {
  name: 'init',
  description: 'Set up GDS in your project — agent docs, theme, and conventions',
  usage: 'gds init [--features agents] [--agent claude|cursor|codex] [--agent-docs-path <path>]',
  args: [],
  options: [
    { name: 'features', description: 'Features to set up (comma-separated: agents, theme, storybook)' },
    { name: 'agent', description: 'Agent format: claude, cursor, or codex (default: claude)' },
    { name: 'agent-docs-path', description: 'Custom path for agent docs file' },
  ],
  run: (args, options) => {
    const features = (options.features as string)?.split(',') || [];
    const agent = (options.agent as string) || 'claude';
    const agentDocsPath = options['agent-docs-path'] as string;

    if (features.includes('agents') || features.length === 0) {
      generateAgentDocs(agent, agentDocsPath);
    }

    if (features.includes('theme') || features.length === 0) {
      console.log('\n📦 Theme setup:');
      console.log('   1. npm install @gds/core @gds/theme-neutral');
      console.log('   2. Add to your global CSS:');
      console.log('      @import "@gds/core/reset.css";');
      console.log('      @import "@gds/core/gds.css";');
      console.log('      @import "@gds/theme-neutral/theme.css";');
    }

    if (features.includes('storybook')) {
      console.log('\n📖 Storybook setup:');
      console.log('   See https://gds.dev/docs/storybook for guide');
    }

    console.log('\n✅ Setup complete!');
  },
};

function generateAgentDocs(agent: string, customPath?: string): void {
  const agentConfig = AGENT_DOCS[agent as keyof typeof AGENT_DOCS] || AGENT_DOCS.claude;
  const filename = customPath || agentConfig.filename;
  const filepath = path.resolve(process.cwd(), filename);

  const content = generateAgentDocContent(agent);

  fs.writeFileSync(filepath, content, 'utf-8');
  console.log(`\n🤖 Agent docs generated: ${filepath}`);
  console.log('   Your AI assistant should read this file before writing GDS code.');
}

function generateAgentDocContent(agent: string): string {
  return `# Generic Design System (GDS) — Agent Guide

> This file teaches AI assistants how to write correct GDS component code.
> Generated by \`gds init --features agents\`. Re-run after version bumps.

## Overview

GDS is a Lit Web Components design system. Components use the \`gds-\` tag prefix,
are framework-agnostic, and use CSS custom properties for theming.

## Before Writing Any UI Code — 3-Step Workflow

1. **\`gds template --list\`** — find a related page pattern to use as reference
2. **\`gds template <name> --skeleton\`** — study the layout structure
3. **\`gds component <Name>\`** — read props and examples for every component used

## Installation

\`\`\`bash
npm install @gds/core @gds/theme-neutral
npm install -D @gds/cli
\`\`\`

## CSS Setup (globals.css)

\`\`\`css
@import '@gds/core/reset.css';
@import '@gds/core/gds.css';
@import '@gds/theme-neutral/theme.css';
\`\`\`

## Importing Components

Components are imported via subpath entrypoints:

\`\`\`ts
import '@gds/core/button';
import '@gds/core/layout';
\`\`\`

Then use as HTML:

\`\`\`html
<gds-vstack gap="2">
  <gds-button label="Hello" variant="primary"></gds-button>
</gds-vstack>
\`\`\`

## Rules (Follow These Strictly)

1. **Use components, not raw HTML.** Don't use \`<div>\` for layout — use \`<gds-vstack>\`, \`<gds-hstack>\`, \`<gds-grid>\`.
2. **Use semantic tokens, not hardcoded values.** Use \`var(--gds-color-primary)\`, not \`#2563eb\`. Use \`var(--gds-space-4)\`, not \`16px\`.
3. **CSS custom properties for colors.** Never use hex values in styles. Always reference tokens.
4. **Form inputs are controlled.** Pass \`value\` and listen for \`input\`/\`change\` events.
5. **No inline styles on raw elements.** Use component props or \`xstyle\` slot.
6. **Don't invent props.** Read \`gds component <Name>\` docs first.

## Available Themes

- \`@gds/theme-neutral\` — Neutral Light (default, muted, minimal)
- \`@gds/theme-dark\` — Neutral Dark (dark mode companion)
- \`@gds/theme-warm\` — Neutral Warm (earthy, warm tones with serif typography)

Switch themes by changing the CSS import. Override individual tokens by setting
CSS custom properties on \`:root\` after the theme import.

## Component Categories

| Category | Components |
|----------|-----------|
| Action | Button, ButtonGroup, IconButton, Link, DropdownMenu, MoreMenu, SegmentedControl, ToggleButton, ToggleButtonGroup, Toolbar |
| Layout | VStack, HStack, Stack, Grid, Container, AspectRatio, Divider, Spacer |
| Content | Avatar, AvatarGroup, Badge, Blockquote, Citation, Icon, Thumbnail, Heading, Text, Code |
| Container | Card, ClickableCard, SelectableCard, Collapsible, Carousel, Banner |
| Form | TextInput, TextArea, NumberInput, Checkbox, Radio, Switch, Slider, Select, Field, FileInput, DateInput, TimeInput |
| Feedback | Toast, Spinner, Progressbar, Skeleton, StatusDot, Tooltip, EmptyState |
| Navigation | Tabs, Breadcrumbs, Pagination, Navigation, AppShell, CommandPalette |
| Overlay | Dialog, Popover, HoverCard, ContextMenu |
| Data | Table, List, Item, TreeList |
| Chat | ChatMessage, ChatComposer, ChatLayout, ChatToolCalls |
| Utility | Kbd, VisuallyHidden |

## Quick Reference: Common Props

### Button
\`\`\`html
<gds-button label="Click me" variant="primary|secondary|ghost|danger|outline" size="sm|md|lg" ?disabled ?loading ?full-width></gds-button>
\`\`\`

### Layout
\`\`\`html
<gds-vstack gap="2|3|4" align="start|center|end|stretch" justify="start|center|end|between">
  <slot/>
</gds-vstack>
\`\`\`

### Card
\`\`\`html
<gds-card variant="default|elevated|outlined" padding="3|4|5">
  <div slot="header">Title</div>
  <div slot="body">Content</div>
  <div slot="footer">Footer</div>
</gds-card>
\`\`\`

### Text Input
\`\`\`html
<gds-text-input value="controlled" placeholder="Type here" ?disabled error="Error message"></gds-text-input>
\`\`\`

### Dialog
\`\`\`html
<gds-dialog ?open title="Dialog" size="sm|md|lg" ?dismissible>
  <div slot="body">Content</div>
  <div slot="footer">Actions</div>
</gds-dialog>
\`\`\`

## CLI Reference

| Command | Purpose |
|---------|---------|
| \`gds init --features agents\` | Generate this file |
| \`gds component --list\` | List all components |
| \`gds component Button\` | Show Button props + examples |
| \`gds template --list\` | List page templates |
| \`gds template dashboard --skeleton\` | Show dashboard layout skeleton |
| \`gds docs theme\` | Show theming guide |
| \`gds docs tokens\` | Show design tokens reference |
| \`gds docs styling\` | Show styling guide |
| \`gds docs layout\` | Show layout guide |
`;
}